### ISSUE TITLE
Slideshow not running in new look or old look.....

### ISSUE THREAD

**Issue by DAVEVANDERMEER** [DMiradakis/Power-BI-Real-Time-Slideshow#3]
Hi Daniel,

First of all what you are doing is so unbelievable useful and critical! Thanks so much. I actually cannot understand why this is not a PBI hot topic as it affects everybody that wants to display reports, dashboards and apps.

I have installed your Chrome extension and that all works fine. However when I confirm save button 2x and click play nothing happens. Also I switched to old look and that does not help. Am I doing something incorrect?

In addition I have a question: Does this only work for 'report' mode in PBI Service or also for 'dashboards' and / or 'apps'? I have deployed an App in 'Apps' and which allows me the to combine different dashboards from different reports to allow me to use different type of dataviews in the slideshow. So should this also work for the APP? Thanks for confirming. 

If you want further info or want me to setup a virtual call to show you just let me know. I can even do tonight if you want that.

Thanks in advance. Best regards, Dave

**Comment by DAVEVANDERMEER** [comment]
Hi Daniel,
Let me know if I was clear or that you need more info. Happy to connect further with you. Dave

**Comment by DMiradakis** [comment]
Hi @DAVEVANDERMEER ,

First off, please allow me to apologize for not responding to you sooner! I just downloaded the GitHub iOS app a week or more ago **specifically** so that I don't keep missing notifications on my repositories, but for some reason I never saw a notification about your issue! I am so sorry for that!

I actually just responded to the user in #2 and apologized for the wait on this. I've been so busy as of late and haven't had a chance to come back to the software to update it!

I am so glad to see that it has activity, though, so I will do my best to update it very soon here! It's so motivating to see people are interested in the extension. : )

In regards to the issues you mentioned:

1. As for your issue regarding it not working in the Power BI "old look", that is most odd... I haven't used it in a while, so let me investigate so that I can get back to you! I am suspicious that perhaps the user interface has changed entirely, both the "old look" as well as the "new look".

2. As for your question regarding dashboards and apps, that, I am afraid, is a bit more tricky... please allow me to respond with a more detailed response tomorrow!

Thanks, and again, I apologize for the wait!

Daniel

**Comment by DMiradakis** [comment]
@DAVEVANDERMEER 

Going off of what I said yesterday, the issue gets quite a bit more tricky with concern to Power BI dashboards and apps.

- Concerning Apps:

I don't actually use Apps myself in Power BI, so I do not quite remember what their UI looks like. From what I remember, I believe it is different from simply opening up a report in a Power BI workspace like a report designer would such as you or I; however, I still use the "old" Power BI workspaces, and I assign the users of my workspaces as having viewing permissions only (I do this for several reasons that work well for me in Power BI). So when I created the extension, I didn't think to take Power BI apps into consideration since I never use them.

Again, from what I remember, I believe the user interface for the same report in an app as in a workspace window looks different depending on if you are viewing it in the app or workspace window.

That being said, I am inclined to say, that, no, this extension will **not** work for Power BI reports in Power BI apps. I would like to verify if I have some time, but I am confident the answer would still be no, unfortunately.

- Concerning Dashboards:

Dashboards are perhaps the trickiest part of your issue. Since a Power BI dashboard enables the pinning of multiple different visuals from multiple different reports, to update all of the visuals in a dashboard would require that each individual Power BI report that the visuals come from themselves be updated.

As you probably know already, the dashboards do have an automatic refresh feature for them, and each tile (pinned visual) on the dashboard can itself be called for a manual refresh.

If, for instance, a bar chart on a dashboard is pinned from a Direct Query/Live Connection Power BI report, then you can expect the dashboard to automatically refresh every 15 minutes because the Direct Query/Live Connection Power BI report can itself be updated.

However - although it seems unclear in the documentation - if your pinned visual in question hails from an Import Mode Power BI report, then the pinned visual is still constrained to how often the Power BI report itself gets updated: last I checked, it is 8 refreshes/day for Pro users and 40 refreshes/day for Premium users on an Import Mode Power BI report.

In either case, the pinned dashboard visual is still constrained to the specific refresh capabilities of the Power BI report that it was pinned from.

If the visuals all belong to Direct Query/Live Connection Power BI reports, then the Power BI service will automatically update your dashboard in question for you. If, however, many of your Power BI reports are Import Mode (such as mine), then we are stuck with that limitation I mentioned above.

Now, the extension I made **bypasses** that limitation using its strong Javascript automation capabilities. I have meticulously investigated the Power BI user interface HTML code, so I know the names of the various elements and buttons within the Power BI Service.

To update a Power BI report, the extension must have a window opened to the Power BI report itself to programatically select and respond to those HTML elements I've found and refresh the report, whether Direct Query/Live Connection or Import Mode.

But this is what I meant earlier when I said the problem was having visuals pinned from multiple different reports onto the same Power BI dashboard: the extension can only refresh one Power BI report at a time. To do more than one, you would need multiple tabs open with the extension activated in each tab to update each report involved in the dashboard.

Only then - and assuming I add Javascript code to programatically select each tile on the dashboard and trigger a manual refresh to the respective report datasets - could the dashboard tiles be updated in near real time.

The way I see it, the issue is two fold:
1. That's a lot of hassle for you to have to open all of those tabs and activate the extension on each tab for a different associated Power BI report, but it _can_ be done.
2. What is ultimately stopping you is that I don't currently have Javscript code in place to handle the user interface for a Power BI dashboard.

I apologize for the long response, but I wanted to explain just why I say the extension won't work for that at the moment without giving a vague "no" as my answer.

I hope that help illuminates the function of the extension!

If you don't mind the hassle of point 1 that I mentioned above, then let me know: perhaps I could consider writing some Javascript code to handle dashboard user interfaces.

Thanks!

Daniel

**Comment by DMiradakis** [comment]
@DAVEVANDERMEER 

Also, would you please provide a video of your chrome window when you open a Power BI report and try to activate the extension? I tested it on the "old" Power BI user interface yesterday evening, and it worked perfectly fine for me on my device. I have a suspicion as to what it _might_ be for you, but if you could provide me an actual video of you attempting to active it, that would be most helpful!

Thanks!

Daniel

**Comment by DMiradakis** [comment]
Hi @DAVEVANDERMEER ,

I hope you are doing well admist this COVID-19 insanity!

I haven't heard back from you in a while, so I'm going to go ahead and close this ticket. However, if you still have issues and would like some assistance later, please let me know! Just respond to this ticket or open a new one!

Thanks!

Best Regards,
Daniel
