### ISSUE TITLE
Slideshow starting/working

### ISSUE THREAD

**Issue by shorkeyr** [DMiradakis/Power-BI-Real-Time-Slideshow#5]
Man, its really awesome that you've built this and you're incredibly prompt in responding to questions/issues. I'm not the best with programming or troubleshooting, so I'm sure this is user error.  However, I downloaded the entire package from the repository, unpackaged it in Chrome, I have the icon in the chrome toolbar, and I've switched the view to the old view where the tabs are at the bottom.  I'm on the pro version, so I don't believe it's related to the server bug that you have. 

I also looked to see if there were any Java setting disabled or blocked, but could seem to figure it out.

**Comment by DMiradakis** [comment]
@shorkeyr 

Thanks so much for the kind words! I've been so busy lately, I haven't been checking my GitHub notifications as quickly as I would like, so thank you again for the encouragement!

I'm sorry to hear about the error you are experiencing! That sounds really odd that you are experiencing that error... especially since you are seeing the icon in the upper right-hand corner of Chrome!

Would you mind taking a video/screen recording of you trying to activate the extension so I can see a little more clearly what exactly is going on? 

Also, if you are able to do a video, then before you begin recording, please follow these steps:
1. Press `Ctrl + Shift + i` on your keyboard. This should bring up the Chrome developer console.
2. Please click on the `Console` tab. This will enable me to see the process logs from the extension while you are attempting to activate it.

If you don't have the ability to take a screen recording, please let me know and I'm sure we can explore another alternative! I personally found a [**wonderful** open source screen recording program](https://www.screentogif.com/) that I use to create GIFs for my documentation; I am sure it would suite your need just fine if you don't have any other programs to do the job.

Thanks!

**Comment by shorkeyr** [comment]
[
![PowerBI Slideshow GIF](https://user-images.githubusercontent.com/66315122/83791737-25404500-a668-11ea-91e0-ee114f5afe9b.gif)
](url)

**Comment by DMiradakis** [comment]
@shorkeyr 

Ah, I think that I see the problem now! It shows that I need to go back and improve the Javascript code for this!

Ok, so I think the issue is that your hamburger menu on the left-hand side of the page is _not_ expanded when you try to activate the extension in your screen recording. I am so used to having that left-hand side nav menu open that I didn't even think to account for the case that someone else may **not** have it expanded.

So, try this out:
Expand the left-hand side nav menu _before_ you activate the extension. Then, try to activate the extension again - just make sure the left-hand side nav menu is expanded when you attempt.

Let me know if this solves your problem!

**Comment by shorkeyr** [comment]
Dang, it still isn't working.

**Comment by DMiradakis** [comment]
@shorkeyr 

I'm sorry to hear that! I'd like to keep investigating! I hate to ask, but can you take another screen recording, only this time have it show the **Chrome developer console** while you do so? Press `Ctrl + Shift + i` and then click the **Console** tab before you start recording and just keep the developer console there while you try to activate the extension!

Having that in your screen recording would really help me out! Thanks!

**Comment by DMiradakis** [comment]
@shorkeyr 

Did you see my last message?

**Comment by joechen1105** [comment]
![FD70C9A3-EB4F-4800-A974-4A632BE7296B](https://user-images.githubusercontent.com/25038598/86141234-cda6c500-babf-11ea-8559-b0afa5c5e732.png)

I don't think it works for me as well, here's the screenshot of my console.

**Comment by DMiradakis** [comment]
@joechen1105 

Thanks for the detailed screenshot! Just to be clear, when the extension is activated, you're saying that it becomes stalled at that point? In other words, it sits on the "Initializing process to determine..." step but never moves forward?

**Comment by joechen1105** [comment]
Yes, it just stuck there and no new notifications were printed on the console.

**Comment by DMiradakis** [comment]
@joechen1105 

Thanks for the information! I am investigating.

**Comment by joechen1105** [comment]
Happy to help, amazing work you have done here.

**Comment by DMiradakis** [comment]
@joechen1105 

I am so sorry for the wait! I've had very little free time the past week and a half, but I haven't forgotten about your ticket! Are you still experiencing the same problem?

**Comment by joechen1105** [comment]
Yes, it has not been resolved yet.

**Comment by DMiradakis** [comment]
@shorkeyr 

I'm so sorry for the wait! Work has kept me super busy lately. I'm looking at the code now, because I actually need to use it for my own work again, as well.

I'll get back to you.

Thanks!

**Comment by DMiradakis** [comment]
@shorkeyr 

Well, I think I'm starting to realize why some things aren't working. The Power BI Team has changed some of their HTML code since my last release on this project, so I'm currently making some code changes.

Still investigating.

**Comment by joechen1105** [comment]
Thank you so much for the follow-up, take your time, really do appreciate it.

**Comment by DMiradakis** [comment]
@joechen1105 

Go to the master branch of this repository and download the files from the commit I just made, please. Has that solved your issue?

**Comment by DMiradakis** [comment]
@joechen1105 

For the device that you try to run this extension on, does it have a slow internet connection, by chance?

**Comment by shorkeyr** [comment]
No, our internet is really fast.

Russell J Shorkey
Love the Customer. Love the Team. Keep it Humble.
Jim Shorkey Family Auto Group
13339 Route 30
North Huntingdon, PA 15642
412-721-2694
www.jimshorkey.com<http://www.jimshorkey.com/>
​

**Comment by DMiradakis** [comment]
All,

I worked on the code for several days last week, and I have just now [pushed out a new release (v2.2.0)](https://github.com/DMiradakis/Power-BI-Real-Time-Slideshow/releases/tag/v2.2.0).

Please download the latest release, as I hope that it will fix your latest problems with the old user interface. I still do not have new code for the new Power BI Service user interface.

Thanks everyone for your patience! Please let me know if you still have issues.

**Comment by shorkeyr** [comment]
Hey Dan, I updated the extension and it seems to still not be working. Not sure where my underlying issue is (and I’m not an overly technical user, so sorry I can’t give much feedback).

Russell J Shorkey
Love the Customer. Love the Team. Keep it Humble.
Jim Shorkey Family Auto Group
13339 Route 30
North Huntingdon, PA 15642
412-721-2694
www.jimshorkey.com<http://www.jimshorkey.com/>
​

**Comment by DMiradakis** [comment]
@shorkeyr 

Are you able to take a screen recording for me that you can upload on here?

If so, ***before you start the recording***, please activate the Chrome Developer Console with the following steps:
1. Press Ctrl + Shift + i on your keyboard. This should bring up the Chrome developer console.
2. Please click on the Console tab. This will enable me to see the process logs from the extension while you are attempting to activate it.

If you can simply get a screen recording or picture of what your Chrome Developer Console is saying, then I can try to be of further assistance.

Thanks!

**Comment by shorkeyr** [comment]
Russell J Shorkey
Love the Customer. Love the Team. Keep it Humble.
Jim Shorkey Family Auto Group
13339 Route 30
North Huntingdon, PA 15642
412-721-2694
www.jimshorkey.com<http://www.jimshorkey.com/>
​

**Comment by DMiradakis** [comment]
@shorkeyr 

Has your issue been resolved? I never did see a response back from you.

Thanks.

**Comment by shorkeyr** [comment]
[Image]

I tried sending this yesterday.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DMiradakis** [comment]
@shorkeyr 

It looks like GitHub isn't picking up your attachment. Can you log _directly into the website_, navigate to this thread, and then attach your file here? I don't think GitHub retains them through responding to me via your email.

Thanks.

**Comment by Dash716** [comment]
@DMiradakis 

Hi Daniel,

Did the HTML code change again? Does it still work for you?

**Comment by Dash716** [comment]
@DMiradakis 

Hi Daniel,

The slide show plug-in suddenly stopped for working for us. Did the HTML code change again?

Does it still work for you?

**Comment by DMiradakis** [comment]
@Dash716 

I just checked again this morning, and the extension is still working for me.

Two questions for you:
1. Are you using the [latest release](https://github.com/DMiradakis/Power-BI-Real-Time-Slideshow/releases/tag/v2.2.1)?
2. Are you using the "Old look" user interface in the Power BI Service?

If your answer to both of those questions is yes, please follow the steps I gave to the people above and do a screen recording for me with your Chrome developer console open.

Thanks!

**Comment by Dash716** [comment]
@DMiradakis 

Thank you for your response. It's already working again.

My problem was in the language settings. Setting the language to English fixed my problem.
